### ISSUE TITLE
version 0.1.1 failing

### ISSUE THREAD

**Issue by priyanshuch** [purifycss/grunt-purifycss#24]
My config.

```
        purifycss: {
            options: {},
            target: {
                src: ['dist/index.html', 'dist/views/**/*.html'],
                css: 'dist/styles/*.css',
                dest: 'dist/styles/min.css'
            },
        },
```

Getting error:
`Warning: this.data.css.forEach is not a function.`

**Comment by kennyt** [comment]
The value for the `css` property should be an array. so `css: ['dist/styles/*.css']`

**Comment by priyanshuch** [comment]
`forEach` it was obvious it was expecting an array :disappointed:  
Thank @kennyt
