### ISSUE TITLE
Register grunt-purifycss with NPM

### ISSUE THREAD

**Issue by nickpeihl** [purifycss/grunt-purifycss#3]
`npm install grunt-purifycss` returns `'grunt-purifycss' is not in the npm registry.`.

**Comment by alexpelan** [comment]
+1

**Comment by iamjpg** [comment]
Iff you want to test this package you can clone the package locally and then install via its local path.

`npm install /path`

Until this is officially published to the NPM registry, this is a work around.

**Comment by mrourke** [comment]
https://www.npmjs.com/package/grunt-purifycss
