### ISSUE TITLE
Options param not working

### ISSUE THREAD

**Issue by kangw3n** [purifycss/grunt-purifycss#7]
Im using sass and compass for my production, 
here's my code in grunt.

```
  purifycss: {
      options: {
        minify: true
      },
      target: {
        src: ['dist/**/*.html', 'dist/js/*.js'], // Observed files
        css: ['dev/css/*.css'], // Take all css files into consideration
        dest: 'dist/css/style.css' // Write to this path
      }
    }
```

CSS can't be minify while i'm running this tasks

**Comment by paskausks** [comment]
I'm experiencing the same issue.

Well, for now I'm just passing the purified file into grunt-contrib-mincss. It's an extra step alright, but it does the trick.

**Comment by tpgmartin** [comment]
It looks like a hardcoded options object was being passed to purify instead of the user-defined options

**Comment by michahell** [comment]
How have you fixed this @tpgmartin ? have no experience building grunt / nodejs tooling :/ disabled this great tool for now, I have the suspicion that some css I need still is getting removed. Together with  missing explicit ignore rules that can be set this isn't yet quite optimal for all use-cases.

**Comment by tpgmartin** [comment]
Hey @michahell I'm not sure I understand. The options parameter relates to the properties defined here https://github.com/purifycss/purifycss#options-optional, none of which explicitly state how much or little CSS should be removed.

This specific fix allows you to pass in the options as desired from your gruntfile.

**Comment by paskausks** [comment]
For me, setting options as `{ minify: true }` doesn't minify the CSS. I think that was the original point of the issue.

**Comment by michahell** [comment]
@tpgmartin setting the `info` parameter to `true` does not give me a list of CSS that has been removed. 
This is handy if you know that some CSS rule that you DO need, is getting removed. you can then either:
- add it to a bogus hidden div, so purify css thinks it is getting used somewhere and does not delete it.
- add it to an 'ignore list', so purifyCSS ignores removing that CSS rule (this does not exist).

I think the original point is that the whole passed options object is not being picked up by PurifyCSS.

**Comment by sjungwirth** [comment]
thanks @tpgmartin for the fix, I guess I'll use your version for now

**Comment by kennyt** [comment]
This is fixed now. Will be publishing as soon as I get permissions on the grunt-purifycss npm package

Edit: done :100:
