### ISSUE TITLE
Ignore certain css rules

### ISSUE THREAD

**Issue by Malm** [purifycss/grunt-purifycss#8]
Is it possible to ignore some rules in my css? I have a couple white are set through combining strings and template-variables like icon-{{role}} which results in eg. .icon-admin. 

Perhaps wrap some rules in css comments like 

``` css
/* ignore */
.icon-admin {}
.icon-user {}
/* endignore */
```

**Comment by msantoro12** [comment]
I am having the same issue in marrionette for backbone. I am setting a class via a url variable.

``` javascript
  className: function() {
    var header = window.location.search.match(/header\=([0-9])/),
        headerNumber = header ? header[1] : 1;

    this.headerVar = headerNumber;

    // these trick it for now
    // header1 header2 header3
    return 'home-page header' + headerNumber;
  }
```

[Trick from here](https://github.com/purifycss/purifycss/issues/66)

**Comment by kennyt** [comment]
There is a whitelist feature now. [See here](https://github.com/purifycss/purifycss#properties-of-options-object)
